#! docker-compose automatically loads environment variables from .env files

## ==== NETWORKS ============================================================ ##
## Defines the custom networks to be created and used by the services.
networks:
  meteor-madness-network:
    # IP Address Management settings: default driver, subnet in CIDR format.
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16


## ==== SERVICES ============================================================ ##
## Defines the services (containers) that make up the application.
## Service names ar arbitrary and used for automatic container name generation.
## Service names are used for DNS resolution inside the Docker private network.
services:

    # ==== NODE ============================================================== #
    be-node:
        container_name: be-node
        image: be-node:latest

        # Build image from Dockerfile in the current directory and override its CMD.
        build:
            context: ./be-node
            dockerfile: Dockerfile
        command: npm run start

        ports:
            - "8001:8000"
        networks:
             - meteor-madness-network

volumes:
    mariadb_data: